/* PF2e hazard traits, and the traits on hazards' actions, with how often they appear together —
   distilled from the 565 hazards on Archives of Nethys (legacy and remastered, 2026-09). "near" holds each
   trait's strongest companions (co-count x lift), so the picker can suggest what usually goes with
   what is already chosen. Complex/Simple are left out: the kicker line already carries complexity.
   Hazard groups: k kind of hazard, r rarity, t everything else. Actions: one group, commonest first. */
var HAZ_TRAITS = {
  hazard:{
    order:"k,r,t",
    r:"Uncommon,Rare,Unique",
    k:"Trap,Haunt,Environmental,Mechanical,Magical,Mythic,Kaiju",
    t:"Fire,Fungus,Divine,Illusion,Evocation,Mental,Electricity,Cold,Nightmare,Visual,Arcane,Primal,Water,Alchemical,Sonic,Conjuration,Curse,Shadow,Plant,Acid,Void,Teleportation,Necromancy,Auditory,Negative,Poison,Elemental,Occult,Steam,Incapacitation,Clockwork,Enchantment,Polymorph,Abjuration,Force,Beast,Unholy,Fear,Air,Animal,Snare,Transmutation,Holy",
    near:{"Trap":"Magical,Mechanical,Uncommon,Unique,Rare,Illusion,Cold,Electricity","Magical":"Trap,Uncommon,Unique,Rare,Illusion,Visual,Mental,Cold","Mechanical":"Trap,Uncommon,Magical,Unique,Electricity,Rare","Haunt":"Unique,Uncommon,Rare,Mythic,Magical,Trap","Unique":"Mythic,Haunt,Magical,Environmental,Trap,Arcane,Divine,Illusion","Environmental":"Fire,Fungus,Unique,Kaiju,Rare,Mythic,Plant,Magical","Uncommon":"Trap,Magical,Mechanical,Haunt,Environmental,Fire","Rare":"Kaiju,Magical,Nightmare,Environmental,Primal,Trap,Divine,Mythic","Mythic":"Primal,Unique,Arcane,Kaiju,Illusion,Environmental,Rare,Magical","Fire":"Water,Environmental,Trap,Unique,Magical,Rare,Uncommon","Kaiju":"Primal,Divine,Rare,Evocation,Mythic,Environmental","Fungus":"Environmental","Divine":"Kaiju,Rare,Unique,Environmental,Magical,Trap","Illusion":"Visual,Mental,Mythic,Magical,Trap,Unique","Evocation":"Electricity,Kaiju,Magical,Trap,Environmental","Mental":"Illusion,Magical,Trap","Electricity":"Evocation,Trap,Rare,Magical,Mechanical","Cold":"Trap,Magical","Nightmare":"Rare","Visual":"Illusion,Magical,Trap","Arcane":"Mythic,Unique","Primal":"Kaiju,Mythic,Rare","Water":"Fire,Environmental","Alchemical":"Environmental","Sonic":"Magical,Trap","Conjuration":"Teleportation,Magical,Trap","Curse":"Trap,Magical","Shadow":"Magical,Trap","Plant":"Environmental","Acid":"Trap","Void":"Negative,Necromancy,Magical,Trap","Teleportation":"Conjuration","Necromancy":"Negative,Void,Magical,Trap","Negative":"Void,Necromancy,Magical,Trap","Poison":"Magical"}
  },
  action:{
    order:"t",
    t:"mental,occult,divine,arcane,emotion,fear,attack,evocation,enchantment,illusion,necromancy,incapacitation,fire,conjuration,poison,sonic,auditory,primal,abjuration,death,force,cold,curse,electricity,teleportation,summon,visual,acid,negative,air,light,transmutation,water,linguistic,shadow,sleep,earth,magical,divination,void,detection,holy,nonlethal,healing,darkness,charm,move,vitality,inhaled,manipulate,concentrate",
    near:{"mental":"emotion,fear,enchantment,occult,illusion,incapacitation,auditory,sleep","occult":"mental,fear,emotion,illusion,enchantment,incapacitation,auditory,death","divine":"necromancy,fire,evocation,abjuration,death,mental,incapacitation,transmutation","arcane":"conjuration,teleportation,evocation,summon,electricity,acid,illusion,mental","emotion":"fear,mental,enchantment,occult,auditory,death,illusion,curse","fear":"emotion,mental,occult,enchantment,auditory,death,illusion,divine","attack":"necromancy","evocation":"arcane,electricity,force,sonic,divine,cold,fire,occult","enchantment":"mental,emotion,fear,occult,incapacitation,auditory,linguistic,curse","illusion":"mental,death,occult,fear,emotion,visual,incapacitation,arcane","necromancy":"divine,negative,death,curse,occult,incapacitation,attack,mental","incapacitation":"sleep,linguistic,mental,visual,enchantment,occult,divine,illusion","fire":"divine,earth,water,evocation,arcane","conjuration":"summon,arcane,teleportation,divine,occult","poison":"mental,primal,divine","sonic":"auditory,evocation,occult,divine","auditory":"mental,fear,emotion,sonic,enchantment,occult,incapacitation","primal":"poison,mental,emotion,fear","abjuration":"force,divine,occult,arcane","death":"illusion,fear,emotion,necromancy,mental,divine,occult","force":"evocation,abjuration,divine,occult","cold":"shadow,evocation","curse":"enchantment,emotion,necromancy,occult,mental,divine","electricity":"evocation,arcane","teleportation":"conjuration,arcane","summon":"conjuration,arcane,divine","visual":"incapacitation,mental,illusion,occult,divine","acid":"arcane","negative":"necromancy","transmutation":"divine","water":"fire","linguistic":"incapacitation,enchantment,mental","shadow":"cold","sleep":"incapacitation,mental","earth":"fire"}
  }
};
